using System;
using System.Linq;
using UniInject;
using UniRx;
using UnityEngine;
using UnityEngine.UIElements;

// Disable warning about fields that are never assigned, their values are injected.
#pragma warning disable CS0649

public class SongSelectEntryControl : INeedInjection, IInjectionFinishedListener, IDisposable
{
    public const float MaxClickDistanceThresholdInPx = 5f;

    [Inject]
    private SongRouletteControl songRouletteControl;

    [Inject]
    private SongSelectSceneControl songSelectSceneControl;

    [Inject]
    private PlaylistManager playlistManager;

    [Inject(UxmlName = R.UxmlNames.songImageOuter)]
    private VisualElement songImageOuter;

    [Inject(UxmlName = R.UxmlNames.songImageInner)]
    private VisualElement songImageInner;

    [Inject(UxmlName = R.UxmlNames.songArtist)]
    private Label songArtist;

    [Inject(UxmlName = R.UxmlNames.songTitle)]
    private Label songTitle;

    [Inject(UxmlName = R.UxmlNames.songEntryFavoriteIcon)]
    private VisualElement favoriteIcon;

    [Inject(UxmlName = R.UxmlNames.songEntryDuetIcon)]
    private VisualElement duetIcon;

    [Inject(UxmlName = R.UxmlNames.songEntryAutoGeneratedIcon)]
    private VisualElement songEntryAutoGeneratedIcon;

    [Inject(UxmlName = R.UxmlNames.songEntryRemoteSourceIcon)]
    private VisualElement songEntryRemoteSourceIcon;

    [Inject(UxmlName = R.UxmlNames.songEntryUiRoot)]
    private VisualElement songEntryUiRoot;

    [Inject(UxmlName = R.UxmlNames.openSongMenuButton)]
    private Button openSongMenuButton;

    [Inject(UxmlName = R.UxmlNames.notAvailableInOnlineGameIcon)]
    private VisualElement notAvailableInOnlineGameIcon;

    [Inject]
    private CreateSingAlongSongControl createSingAlongSongControl;

    [Inject]
    private AudioSeparationManager audioSeparationManager;

    [Inject]
    private SongMetaManager songMetaManager;

    [Inject]
    private UiManager uiManager;

    [Inject]
    private Injector injector;

    [Inject]
    private Settings settings;

    private TooltipControl songEntryRemoteSourceIconTooltipControl;

    /**
     * Name for debugging purpose
     */
    public string Name { get; set; }

    private SongSelectEntry songSelectEntry;
    public SongSelectEntry SongSelectEntry
    {
        get => songSelectEntryProperty.Value;
        set => songSelectEntryProperty.Value = value;
    }

    private readonly ReactiveProperty<SongSelectEntry> songSelectEntryProperty = new();
    public IObservable<SongSelectEntry> SongSelectEntryAsObservable => songSelectEntryProperty;

    [Inject(Key = Injector.RootVisualElementInjectionKey)]
    public VisualElement VisualElement { get; private set; }

    private ContextMenuControl contextMenuControl;
    private bool isPopupMenuOpen;
    private float popupMenuClosedTimeInSeconds;

    private readonly Subject<VoidEvent> clickOnSongImageEventStream = new();
    public IObservable<VoidEvent> ClickOnSongImageEventStream => clickOnSongImageEventStream;

    private bool isInitialized;

    private readonly SongSelectSongRatingIconControl songRatingIconControl = new();

    private Vector2 pointerDownMousePosition;

    private string lastSongMetaCover;
    private string lastSongMetaBackground;

    public void OnInjectionFinished()
    {
        Init();
        RegisterCallbacks();
    }

    private void RegisterCallbacks()
    {
        VisualElement.RegisterCallback<PointerUpEvent>(OnPointerUp, TrickleDown.TrickleDown);
        songImageOuter.RegisterCallback<PointerDownEvent>(OnPointerDownOnSongImage, TrickleDown.TrickleDown);
        songImageOuter.RegisterCallback<PointerUpEvent>(OnPointerUpOnSongImage, TrickleDown.TrickleDown);
        openSongMenuButton.RegisterCallbackButtonTriggered(OnOpenSongMenuButtonClicked);
    }

    private void UnregisterCallbacks()
    {
        VisualElement.UnregisterCallback<PointerUpEvent>(OnPointerUp, TrickleDown.TrickleDown);
        songImageOuter.UnregisterCallback<PointerDownEvent>(OnPointerDownOnSongImage, TrickleDown.TrickleDown);
        songImageOuter.UnregisterCallback<PointerUpEvent>(OnPointerUpOnSongImage, TrickleDown.TrickleDown);
        openSongMenuButton.UnregisterCallbackButtonTriggered(OnOpenSongMenuButtonClicked);
    }

    private void Init()
    {
        if (isInitialized)
        {
            return;
        }
        isInitialized = true;

        injector.Inject(songRatingIconControl);

        songEntryRemoteSourceIconTooltipControl = new(songEntryRemoteSourceIcon);

        InitSongMenu();

        playlistManager.PlaylistChangeEventStream
            .Subscribe(evt => UpdateIcons());

        settings.ObserveEveryValueChanged(it => it.Difficulty)
            .Subscribe(_ => UpdateIcons());

        SongSelectEntryAsObservable.Subscribe(newValue => OnSongSelectEntryChanged(newValue));
    }

    private void OnSongSelectEntryChanged(SongSelectEntry newValue)
    {
        VisualElement.SetVisibleByVisibility(newValue != null);
        UpdateLabels();
        UpdateIcons();
        UpdateCover();
    }

    private void InitSongMenu()
    {
        contextMenuControl = injector
            .WithRootVisualElement(openSongMenuButton)
            .CreateAndInject<ContextMenuControl>();
        contextMenuControl.FillContextMenuAction = FillContextMenu;
        contextMenuControl.ContextMenuOpenedEventStream.Subscribe(OnContextMenuOpened);
        contextMenuControl.ContextMenuClosedEventStream.Subscribe(OnContextMenuClosed);
    }

    private void OnPointerDownOnSongImage(PointerDownEvent evt)
    {
        pointerDownMousePosition = evt.position;
    }

    private void OnPointerUpOnSongImage(PointerUpEvent evt)
    {
        if (evt.button == 0
            && Vector2.Distance(pointerDownMousePosition ,evt.position) < MaxClickDistanceThresholdInPx)
        {
            clickOnSongImageEventStream.OnNext(VoidEvent.instance);
        }
    }

    private void OnPointerUp(PointerUpEvent evt)
    {
        // Open context menu on right click
        if (evt.button == 1
            && !isPopupMenuOpen
            && TimeUtils.IsDurationAboveThresholdInSeconds(popupMenuClosedTimeInSeconds, 0.1f))
        {
            contextMenuControl.OpenContextMenu(evt.position, this);
        }
    }

    private void OnOpenSongMenuButtonClicked(EventBase evt)
    {
        if (isPopupMenuOpen
            || !TimeUtils.IsDurationAboveThresholdInSeconds(popupMenuClosedTimeInSeconds, 0.1f))
        {
            return;
        }

        contextMenuControl.OpenContextMenu(new Vector2(-1, -1), this);
    }

    private void FillContextMenu(ContextMenuPopupControl contextMenuPopup)
    {
        Debug.Log($"Context: {contextMenuPopup.Context}");
        if (SongSelectEntry is SongSelectSongEntry songEntry)
        {
            FillSongEntryContextMenu(contextMenuPopup, songEntry);
        }
        else if (SongSelectEntry is SongSelectFolderEntry folderEntry)
        {
            FillFolderEntryContextMenu(contextMenuPopup, folderEntry);
        }
    }

    private void FillSongEntryContextMenu(ContextMenuPopupControl contextMenuPopup, SongSelectSongEntry songEntry)
    {
        // Start song
        contextMenuPopup.AddButton(Translation.Get(R.Messages.songSelectScene_action_start), "play_arrow",
            () =>
            {
                songSelectSceneControl.AttemptStartEntry(songEntry);
            });

        // Add / remove from playlist
        playlistManager.Playlists
            .Where(playlist => playlist is UltraStarPlaylist
                               && playlist is not UltraStarAllSongsPlaylist)
            .ForEach(playlist =>
            {
                UltraStarPlaylist ultraStarPlaylist = playlist as UltraStarPlaylist;
                string playlistName = playlist.Name;
                if (playlistManager.HasSongEntry(playlist, songEntry.SongMeta))
                {
                    contextMenuPopup.AddButton(Translation.Get(R.Messages.songSelectScene_action_removeFromPlaylist,
                            "playlist", playlistName), "favorite_border", R.Messages.songSelectScene_action_removeFromPlaylist,
                        () => playlistManager.RemoveSongFromPlaylist(ultraStarPlaylist, songEntry.SongMeta));
                }
                else
                {
                    contextMenuPopup.AddButton(Translation.Get(R.Messages.songSelectScene_action_addToPlaylist,
                            "playlist", playlistName), "favorite", R.Messages.songSelectScene_action_addToPlaylist,
                        () => playlistManager.AddSongToPlaylist(ultraStarPlaylist, songEntry.SongMeta));
                }
            });

        contextMenuPopup.AddButton(Translation.Get(R.Messages.songQueue_action_add), "playlist_add",
            () =>
            {
                songSelectSceneControl.AddSongToSongQueue(songEntry.SongMeta);
            });

        contextMenuPopup.AddButton(Translation.Get(R.Messages.songQueue_action_addAsMedley), "link",
            () =>
            {
                songSelectSceneControl.AddSongToSongQueueAsMedley(songEntry.SongMeta);
            });

        // Open song editor / song folder
        contextMenuPopup.AddButton(Translation.Get(R.Messages.action_openSongEditor), "edit",
            () => songSelectSceneControl.StartSongEditorScene());
        if (PlatformUtils.IsStandalone)
        {
            if (DirectoryUtils.Exists(SongMetaUtils.GetDirectoryPath(songEntry.SongMeta)))
            {
                contextMenuPopup.AddButton(Translation.Get(R.Messages.action_openFolder), "open_in_new",
                    () => SongMetaUtils.OpenDirectory(songEntry.SongMeta));
            }
            contextMenuPopup.AddButton(Translation.Get(R.Messages.action_reloadSong), "replay",
                () => songMetaManager.ReloadSong(songEntry.SongMeta));
        }

        if (Application.isEditor)
        {
            // TODO: enable the "recreate song" feature in production when AI tools are running on Unity API?
            contextMenuPopup.AddButton(Translation.Get(R.Messages.action_recreateSong), "replay_circle_filled",
            () => songSelectSceneControl.AskToRecreateSingAlongData(songEntry.SongMeta));
        }

        contextMenuPopup.AddButton(Translation.Get(R.Messages.action_showInfo), "lyrics",
            () =>
            {
                songSelectSceneControl.ShowLyricsAndInfoPopup(songEntry.SongMeta);
            });

        VisualElement buttonContainer = contextMenuPopup.AddButton(Translation.Get(R.Messages.action_separateAudio), "call_split",
            () =>
            {
                audioSeparationManager.ProcessSongMeta(songEntry.SongMeta, true);
            });

        // Disable button if vocals and instrumental audio already exist.
        if (SongMetaUtils.VocalsAudioResourceExists(songEntry.SongMeta)
            && SongMetaUtils.InstrumentalAudioResourceExists(songEntry.SongMeta))
        {
            buttonContainer.Q<Button>().SetEnabled(false);
        }
    }

    private void FillFolderEntryContextMenu(ContextMenuPopupControl contextMenuPopup, SongSelectFolderEntry folderEntry)
    {
        if (PlatformUtils.IsStandalone)
        {
            if (DirectoryUtils.Exists(folderEntry.DirectoryInfo.FullName))
            {
                contextMenuPopup.AddButton(Translation.Get(R.Messages.action_openFolder), "open_in_new",
                    () => ApplicationUtils.OpenDirectory(folderEntry.DirectoryInfo.FullName));
            }
        }
    }

    private void OnContextMenuClosed(ContextMenuPopupControl contextMenuPopupControl)
    {
        isPopupMenuOpen = false;
        popupMenuClosedTimeInSeconds = Time.time;
    }

    private void OnContextMenuOpened(ContextMenuPopupControl contextMenuPopupControl)
    {
        isPopupMenuOpen = true;
        if (contextMenuPopupControl.Position.x < 0
            || contextMenuPopupControl.Position.y < 0)
        {
            new AnchoredPopupControl(contextMenuPopupControl.VisualElement, openSongMenuButton, Corner2D.BottomLeft);
        }
        contextMenuPopupControl.VisualElement.AddToClassList("singSceneContextMenu");
    }

    private void UpdateCover()
    {
        notAvailableInOnlineGameIcon.HideByDisplay();

        if (SongSelectEntry is SongSelectSongEntry songEntry)
        {
            UpdateSongCover(songEntry);
        }
        else if (SongSelectEntry is SongSelectFolderEntry folderEntry)
        {
            SetDefaultFolderImage();
        }
        else
        {
            SetDefaultSongCoverImageWithColor();
        }
    }

    private void UpdateSongCover(SongSelectSongEntry songEntry)
    {
        SongMeta songMeta = songEntry.SongMeta;
        lastSongMetaCover = songMeta.Cover;
        lastSongMetaBackground = songMeta.Background;

        SongMetaImageUtils.GetCoverOrBackgroundImageUri(songMeta)
            .SelectMany(uri =>
            {
                if (SongEntryChanged(songMeta))
                {
                    // The entry changed in the meantime
                    return Observable.Return<Sprite>(null);
                }

                if (uri.IsNullOrEmpty())
                {
                    return Observable.Return<Sprite>(null);
                }

                return ImageManager.LoadSpriteFromUri(uri);
            })
            .CatchIgnore((Exception ex) =>
            {
                Debug.LogException(ex);

                if (SongEntryChanged(songMeta))
                {
                    // The entry changed in the meantime
                    return;
                }
                SongMetaImageUtils.SetDefaultSongImageAndColor(songMeta, songImageOuter, songImageInner);
            })
            .Subscribe(sprite =>
            {
                if (SongEntryChanged(songMeta))
                {
                    // The entry changed in the meantime
                    return;
                }

                if (sprite == null)
                {
                    SongMetaImageUtils.SetDefaultSongImageAndColor(songMeta, songImageOuter, songImageInner);
                    return;
                }

                SongMetaImageUtils.SetCoverOrBackgroundImage(sprite, songImageOuter, songImageInner);
            });

        notAvailableInOnlineGameIcon.HideByDisplay();
    }

    public void ShowNotAvailableInOnlineGameIcon()
    {
        notAvailableInOnlineGameIcon.ShowByDisplay();
    }

    private bool SongEntryChanged(SongMeta songMeta)
    {
        return !IsSongEntry(songMeta);
    }

    private bool IsSongEntry(SongMeta songMeta)
    {
        return SongSelectEntry is SongSelectSongEntry songSelectSongEntry
               && songSelectSongEntry.SongMeta == songMeta;
    }

    private void SetDefaultFolderImage()
    {
        songImageOuter.style.backgroundImage = new StyleBackground(UiManager.Instance.defaultFolderImage);
        songImageOuter.style.unityBackgroundImageTintColor = new StyleColor(Color.white);

        songImageInner.style.backgroundImage = new StyleBackground(UiManager.Instance.defaultFolderImage);
        songImageInner.style.unityBackgroundImageTintColor = new StyleColor(Color.white);
    }

    private void SetDefaultSongCoverImageWithColor()
    {
        SongMetaImageUtils.SetDefaultSongImage(songImageOuter, songImageInner);
        if (songSelectEntry is SongSelectSongEntry songEntry)
        {
            SongMetaImageUtils.SetDefaultSongImageColor(songEntry.SongMeta, songImageOuter, songImageInner);
        }
        else
        {
            songImageOuter.style.unityBackgroundImageTintColor = new StyleColor(StyleKeyword.Undefined);
            songImageInner.style.unityBackgroundImageTintColor = new StyleColor(StyleKeyword.Undefined);
        }
    }

    private void UpdateIcons()
    {
        if (SongSelectEntry is SongSelectSongEntry songEntry)
        {
            UpdateSongIcons(songEntry);
        }
        else
        {
            favoriteIcon.HideByDisplay();
            duetIcon.HideByDisplay();
            songEntryAutoGeneratedIcon.HideByDisplay();
            songEntryRemoteSourceIcon.HideByDisplay();
            songEntryRemoteSourceIconTooltipControl.TooltipText = Translation.Empty;
            songRatingIconControl.HideSongRatingIcons();
        }
    }

    private void UpdateSongIcons(SongSelectSongEntry songEntry)
    {
        favoriteIcon.SetVisibleByDisplay(playlistManager.FavoritesPlaylist.HasSongEntry(songEntry.SongMeta));
        duetIcon.SetVisibleByDisplay(songEntry.SongMeta.VoiceCount > 1);
        songEntryAutoGeneratedIcon.SetVisibleByDisplay(!SongMetaUtils.HasSingAlongData(songEntry.SongMeta));
        songEntryRemoteSourceIcon.SetVisibleByDisplay(!songEntry.SongMeta.RemoteSource.IsNullOrEmpty());
        songEntryRemoteSourceIconTooltipControl.TooltipText = Translation.Of(songEntry.SongMeta.RemoteSource.NullToEmpty());
        songRatingIconControl.UpdateSongRatingIcons(songEntry.SongMeta, settings.Difficulty);
    }

    private void UpdateLabels()
    {
        if (SongSelectEntry is SongSelectSongEntry songEntry)
        {
            songArtist.SetTranslatedText(Translation.Of(songEntry.SongMeta.Artist));
            songTitle.SetTranslatedText(Translation.Of(songEntry.SongMeta.Title));
        }
        else if (SongSelectEntry is SongSelectFolderEntry folderEntry)
        {
            songTitle.SetTranslatedText(Translation.Of(folderEntry.DirectoryInfo.Name));
            songArtist.SetTranslatedText(Translation.Empty);
        }
        else
        {
            songTitle.SetTranslatedText(Translation.Empty);
            songArtist.SetTranslatedText(Translation.Empty);
        }
    }

    public void Dispose()
    {
        SongSelectEntry = null;
        UnregisterCallbacks();
    }

    public void OpenContextMenu()
    {
        if (!isPopupMenuOpen)
        {
            ContextMenuPopupControl contextMenuPopupControl = contextMenuControl?.OpenContextMenu(
                new Vector2(openSongMenuButton.worldBound.xMin, openSongMenuButton.worldBound.yMin),
                this);
            contextMenuPopupControl?.VisualElement.Q<Button>().Focus();
        }
    }

    public void Update()
    {
        if (SongSelectEntry is SongSelectSongEntry songEntry
            && (songEntry.SongMeta?.Cover != lastSongMetaCover
                || songEntry.SongMeta?.Background != lastSongMetaBackground))
        {
            Debug.Log($"Updating cover image because cover or background changed in song '{songEntry.SongMeta.GetArtistDashTitle()}'");
            UpdateCover();
        }
    }
}
