using System;
using System.Linq;
using CommonOnlineMultiplayer;
using ProTrans;
using UniInject;
using UniRx;
using UnityEngine;
using UnityEngine.UIElements;

// Disable warning about fields that are never assigned, their values are injected.
#pragma warning disable CS0649

public class SongSelectEntryControl : INeedInjection, IInjectionFinishedListener, IDisposable
{
    [Inject]
    private SongRouletteControl songRouletteControl;

    [Inject]
    private SongSelectSceneControl songSelectSceneControl;

    [Inject]
    private PlaylistManager playlistManager;

    [Inject(UxmlName = R.UxmlNames.songImageOuter)]
    private VisualElement songImageOuter;

    [Inject(UxmlName = R.UxmlNames.songImageInner)]
    private VisualElement songImageInner;

    [Inject(UxmlName = R.UxmlNames.songArtist)]
    private Label songArtist;

    [Inject(UxmlName = R.UxmlNames.songTitle)]
    private Label songTitle;

    [Inject(UxmlName = R.UxmlNames.songEntryFavoriteIcon)]
    private VisualElement favoriteIcon;

    [Inject(UxmlName = R.UxmlNames.songEntryDuetIcon)]
    private VisualElement duetIcon;

    [Inject(UxmlName = R.UxmlNames.songEntryAutoGeneratedIcon)]
    private VisualElement songEntryAutoGeneratedIcon;

    [Inject(UxmlName = R.UxmlNames.songEntryRemoteSourceIcon)]
    private VisualElement songEntryRemoteSourceIcon;

    [Inject(UxmlName = R.UxmlNames.songEntryUiRoot)]
    private VisualElement songEntryUiRoot;

    [Inject(UxmlName = R.UxmlNames.openSongMenuButton)]
    private Button openSongMenuButton;

    [Inject(UxmlName = R.UxmlNames.notAvailableInOnlineGameIcon)]
    private VisualElement notAvailableInOnlineGameIcon;

    [Inject]
    private OnlineMultiplayerManager onlineMultiplayerManager;

    [Inject]
    private CreateSingAlongSongControl createSingAlongSongControl;

    [Inject]
    private AudioSeparationManager audioSeparationManager;

    [Inject]
    private SongMetaManager songMetaManager;

    [Inject]
    private UiManager uiManager;

    [Inject]
    private Injector injector;

    [Inject]
    private Settings settings;

    private TooltipControl songEntryRemoteSourceIconTooltipControl;

    /**
     * Name for debugging purpose
     */
    public string Name { get; set; }

    private SongSelectEntry songSelectEntry;
    public SongSelectEntry SongSelectEntry
    {
        get
        {
            return songSelectEntry;
        }
        set
        {
            songSelectEntry = value;
            VisualElement.SetVisibleByVisibility(songSelectEntry != null);
            UpdateLabels();
            UpdateIcons();
            UpdateCover();
        }
    }

    [Inject(Key = Injector.RootVisualElementInjectionKey)]
    public VisualElement VisualElement { get; private set; }

    private ContextMenuControl contextMenuControl;
    private bool isPopupMenuOpen;
    private float popupMenuClosedTimeInSeconds;

    private readonly Subject<bool> clickOnSongImageEventStream = new();
    public IObservable<bool> ClickOnSongImageEventStream => clickOnSongImageEventStream;

    private bool isInitialized;

    private readonly SongSelectSongRatingIconControl songRatingIconControl = new();

    private Vector2 pointerDownMousePosition;
    private bool wasSelectedOnPointerDown;

    private string lastSongMetaCover;
    private string lastSongMetaBackground;

    public void OnInjectionFinished()
    {
        Init();
        RegisterCallbacks();
    }

    private void RegisterCallbacks()
    {
        VisualElement.RegisterCallback<PointerUpEvent>(OnPointerUp, TrickleDown.TrickleDown);
        songImageOuter.RegisterCallback<PointerDownEvent>(OnPointerDownOnSongImage, TrickleDown.TrickleDown);
        songImageOuter.RegisterCallback<PointerUpEvent>(OnPointerUpOnSongImage, TrickleDown.TrickleDown);
        openSongMenuButton.RegisterCallbackButtonTriggered(OnOpenSongMenuButtonClicked);
    }

    private void UnregisterCallbacks()
    {
        VisualElement.UnregisterCallback<PointerUpEvent>(OnPointerUp, TrickleDown.TrickleDown);
        songImageOuter.UnregisterCallback<PointerDownEvent>(OnPointerDownOnSongImage, TrickleDown.TrickleDown);
        songImageOuter.UnregisterCallback<PointerUpEvent>(OnPointerUpOnSongImage, TrickleDown.TrickleDown);
        openSongMenuButton.UnregisterCallbackButtonTriggered(OnOpenSongMenuButtonClicked);
    }

    private void Init()
    {
        if (isInitialized)
        {
            return;
        }
        isInitialized = true;

        injector.Inject(songRatingIconControl);

        songEntryRemoteSourceIconTooltipControl = new(songEntryRemoteSourceIcon);

        InitSongMenu();

        playlistManager.PlaylistChangeEventStream
            .Subscribe(evt => UpdateIcons());

        settings.ObserveEveryValueChanged(it => it.Difficulty)
            .Subscribe(_ => UpdateIcons());
    }

    private void InitSongMenu()
    {
        contextMenuControl = injector
            .WithRootVisualElement(openSongMenuButton)
            .CreateAndInject<ContextMenuControl>();
        contextMenuControl.FillContextMenuAction = FillContextMenu;
        contextMenuControl.ContextMenuOpenedEventStream.Subscribe(OnContextMenuOpened);
        contextMenuControl.ContextMenuClosedEventStream.Subscribe(OnContextMenuClosed);
    }

    private void OnPointerDownOnSongImage(PointerDownEvent evt)
    {
        pointerDownMousePosition = evt.position;
        wasSelectedOnPointerDown = songRouletteControl.SelectedEntryControl == this;
    }

    private void OnPointerUpOnSongImage(PointerUpEvent evt)
    {
        if (evt.button == 0
            && Vector2.Distance(pointerDownMousePosition ,evt.position) < 5f
            && wasSelectedOnPointerDown)
        {
            clickOnSongImageEventStream.OnNext(true);
        }
    }

    private void OnPointerUp(PointerUpEvent evt)
    {
        // Open context menu on right click
        if (evt.button == 1
            && !isPopupMenuOpen
            && TimeUtils.IsDurationAboveThresholdInSeconds(popupMenuClosedTimeInSeconds, 0.1f))
        {
            contextMenuControl.OpenContextMenu(evt.position);
        }
    }

    private void OnOpenSongMenuButtonClicked(EventBase evt)
    {
        if (isPopupMenuOpen
            || !TimeUtils.IsDurationAboveThresholdInSeconds(popupMenuClosedTimeInSeconds, 0.1f))
        {
            return;
        }

        contextMenuControl.OpenContextMenu(new Vector2(-1, -1));
    }

    private void FillContextMenu(ContextMenuPopupControl contextMenuPopup)
    {
        if (SongSelectEntry is SongSelectSongEntry songEntry)
        {
            FillSongEntryContextMenu(contextMenuPopup, songEntry);
        }
        else if (SongSelectEntry is SongSelectFolderEntry folderEntry)
        {
            FillFolderEntryContextMenu(contextMenuPopup, folderEntry);
        }
    }

    private void FillSongEntryContextMenu(ContextMenuPopupControl contextMenuPopup, SongSelectSongEntry songEntry)
    {
        // Start song
        contextMenuPopup.AddButton("Start", "play_arrow",
            () =>
            {
                songSelectSceneControl.AttemptStartEntry(songEntry);
            });

        // Add / remove from playlist
        playlistManager.Playlists
            .Where(playlist => playlist is UltraStarPlaylist
                               && playlist is not UltraStarAllSongsPlaylist)
            .ForEach(playlist =>
            {
                UltraStarPlaylist ultraStarPlaylist = playlist as UltraStarPlaylist;
                string playlistName = playlist.Name;
                if (playlistManager.HasSongEntry(playlist, songEntry.SongMeta))
                {
                    contextMenuPopup.AddButton($"Remove from '{playlistName}'", "favorite_border",
                        () => playlistManager.RemoveSongFromPlaylist(ultraStarPlaylist, songEntry.SongMeta));
                }
                else
                {
                    contextMenuPopup.AddButton($"Add to '{playlistName}'", "favorite",
                        () => playlistManager.AddSongToPlaylist(ultraStarPlaylist, songEntry.SongMeta));
                }
            });

        contextMenuPopup.AddButton("Enqueue", "playlist_add",
            () =>
            {
                songSelectSceneControl.AddSongToSongQueue(songEntry.SongMeta);
            });

        contextMenuPopup.AddButton("Enqueue Medley", "link",
            () =>
            {
                songSelectSceneControl.AddSongToSongQueueAsMedley(songEntry.SongMeta);
            });

        // Open song editor / song folder
        contextMenuPopup.AddButton("Open Editor", "edit",
            () => songSelectSceneControl.StartSongEditorScene());
        if (PlatformUtils.IsStandalone)
        {
            if (DirectoryUtils.Exists(SongMetaUtils.GetDirectoryPath(songEntry.SongMeta)))
            {
                contextMenuPopup.AddButton("Open Folder", "open_in_new",
                    () => SongMetaUtils.OpenDirectory(songEntry.SongMeta));
            }
            contextMenuPopup.AddButton("Reload Song", "replay",
                () => songMetaManager.ReloadSong(songEntry.SongMeta));
        }

        contextMenuPopup.AddButton("Recreate Song", "replay_circle_filled",
        () => songSelectSceneControl.AskToRecreateSingAlongData(songEntry.SongMeta));

        contextMenuPopup.AddButton("Info", "lyrics",
            () =>
            {
                songSelectSceneControl.ShowLyricsAndInfoPopup(songEntry.SongMeta);
            });

        VisualElement buttonContainer = contextMenuPopup.AddButton("Vocals Isolation", "call_split",
            () =>
            {
                audioSeparationManager.ProcessSongMeta(songEntry.SongMeta, true);
            });

        // Disable button if vocals and instrumental audio already exist.
        if (SongMetaUtils.VocalsAudioResourceExists(songEntry.SongMeta)
            && SongMetaUtils.InstrumentalAudioResourceExists(songEntry.SongMeta))
        {
            buttonContainer.Q<Button>().SetEnabled(false);
        }
    }

    private void FillFolderEntryContextMenu(ContextMenuPopupControl contextMenuPopup, SongSelectFolderEntry folderEntry)
    {
        if (PlatformUtils.IsStandalone)
        {
            if (DirectoryUtils.Exists(folderEntry.DirectoryInfo.FullName))
            {
                contextMenuPopup.AddButton("Open Folder", "open_in_new",
                    () => ApplicationUtils.OpenDirectory(folderEntry.DirectoryInfo.FullName));
            }
        }
    }

    private void OnContextMenuClosed(ContextMenuPopupControl contextMenuPopupControl)
    {
        isPopupMenuOpen = false;
        popupMenuClosedTimeInSeconds = Time.time;
    }

    private void OnContextMenuOpened(ContextMenuPopupControl contextMenuPopupControl)
    {
        isPopupMenuOpen = true;
        if (contextMenuPopupControl.Position.x < 0
            || contextMenuPopupControl.Position.y < 0)
        {
            new AnchoredPopupControl(contextMenuPopupControl.VisualElement, openSongMenuButton, Corner2D.BottomLeft);
        }
        contextMenuPopupControl.VisualElement.AddToClassList("singSceneContextMenu");
    }

    private void UpdateCover()
    {
        notAvailableInOnlineGameIcon.HideByDisplay();

        if (SongSelectEntry is SongSelectSongEntry songEntry)
        {
            UpdateSongCover(songEntry);
        }
        else if (SongSelectEntry is SongSelectFolderEntry folderEntry)
        {
            SetDefaultFolderImage();
        }
        else
        {
            SetDefaultSongCoverImageWithColor();
        }
    }

    private void UpdateSongCover(SongSelectSongEntry songEntry)
    {
        SongMeta songMeta = songEntry.SongMeta;
        lastSongMetaCover = songMeta.Cover;
        lastSongMetaBackground = songMeta.Background;

        SongMetaImageUtils.GetCoverOrBackgroundImageUri(songMeta)
            .SelectMany(uri =>
            {
                if (SongSelectEntry is not SongSelectSongEntry songSelectSongEntry
                    || songSelectSongEntry.SongMeta != songMeta)
                {
                    // The entry changed in the meantime
                    return Observable.Return<Sprite>(null);
                }

                if (uri.IsNullOrEmpty())
                {
                    return Observable.Return<Sprite>(null);
                }

                return ImageManager.LoadSpriteFromUri(uri);
            })
            .CatchIgnore((Exception ex) =>
            {
                Debug.LogException(ex);

                if (SongSelectEntry is not SongSelectSongEntry songSelectSongEntry
                    || songSelectSongEntry.SongMeta != songMeta)
                {
                    // The entry changed in the meantime
                    return;
                }
                SongMetaImageUtils.SetDefaultSongImageAndColor(songMeta, songImageOuter, songImageInner);
            })
            .Subscribe(sprite =>
            {
                if (SongSelectEntry is not SongSelectSongEntry songSelectSongEntry
                    || songSelectSongEntry.SongMeta != songMeta)
                {
                    // The entry changed in the meantime
                    return;
                }

                if (sprite == null)
                {
                    SongMetaImageUtils.SetDefaultSongImageAndColor(songMeta, songImageOuter, songImageInner);
                    return;
                }

                SongMetaImageUtils.SetCoverOrBackgroundImage(sprite, songImageOuter, songImageInner);
            });

        notAvailableInOnlineGameIcon.HideByDisplay();
        if (onlineMultiplayerManager.IsOnlineGame)
        {
            CheckAllPlayersHaveSongLocally(songMeta);
        }
    }

    private void CheckAllPlayersHaveSongLocally(SongMeta songMeta)
    {
        onlineMultiplayerManager.ObservableMessagingControl.SendNamedMessageToClientsAsObservable(
            nameof(HasSongRequestDto),
            FastBufferWriterUtils.WriteJsonValuePacked(new HasSongRequestDto(SongIdManager.GetAndCacheGloballyUniqueId(songMeta))),
            onlineMultiplayerManager.OtherLobbyMembersUnityNetcodeClientIds)
            .CatchIgnore((Exception ex) =>
            {
                Debug.LogException(ex);
                Debug.LogError($"Failed to check whether all lobby members have song '{SongMetaUtils.GetArtistDashTitle(songMeta)}' locally: {ex.Message}");
            })
            .Subscribe(response =>
            {
                HasSongResponseDto responseDto = FastBufferReaderUtils.ReadJsonValuePacked<HasSongResponseDto>(response.MessagePayload);
                if (!responseDto.HasSong)
                {
                    Debug.Log($"Netcode client {response.SenderNetcodeClientId} does not have the song '{SongMetaUtils.GetArtistDashTitle(songMeta)}', showing corresponding icon.");
                    notAvailableInOnlineGameIcon.ShowByDisplay();
                }
            });
    }

    private void SetDefaultFolderImage()
    {
        songImageOuter.style.backgroundImage = new StyleBackground(UiManager.Instance.defaultFolderImage);
        songImageOuter.style.unityBackgroundImageTintColor = new StyleColor(Color.white);

        songImageInner.style.backgroundImage = new StyleBackground(UiManager.Instance.defaultFolderImage);
        songImageInner.style.unityBackgroundImageTintColor = new StyleColor(Color.white);
    }

    private void SetDefaultSongCoverImageWithColor()
    {
        SongMetaImageUtils.SetDefaultSongImage(songImageOuter, songImageInner);
        if (songSelectEntry is SongSelectSongEntry songEntry)
        {
            SongMetaImageUtils.SetDefaultSongImageColor(songEntry.SongMeta, songImageOuter, songImageInner);
        }
        else
        {
            songImageOuter.style.unityBackgroundImageTintColor = new StyleColor(StyleKeyword.Undefined);
            songImageInner.style.unityBackgroundImageTintColor = new StyleColor(StyleKeyword.Undefined);
        }
    }

    private void UpdateIcons()
    {
        if (SongSelectEntry is SongSelectSongEntry songEntry)
        {
            UpdateSongIcons(songEntry);
        }
        else
        {
            favoriteIcon.HideByDisplay();
            duetIcon.HideByDisplay();
            songEntryAutoGeneratedIcon.HideByDisplay();
            songEntryRemoteSourceIcon.HideByDisplay();
            songEntryRemoteSourceIconTooltipControl.TooltipText = "";
            songRatingIconControl.HideSongRatingIcons();
        }
    }

    private void UpdateSongIcons(SongSelectSongEntry songEntry)
    {
        favoriteIcon.SetVisibleByDisplay(playlistManager.FavoritesPlaylist.HasSongEntry(songEntry.SongMeta));
        duetIcon.SetVisibleByDisplay(songEntry.SongMeta.VoiceCount > 1);
        songEntryAutoGeneratedIcon.SetVisibleByDisplay(!SongMetaUtils.HasSingAlongData(songEntry.SongMeta));
        songEntryRemoteSourceIcon.SetVisibleByDisplay(!songEntry.SongMeta.RemoteSource.IsNullOrEmpty());
        songEntryRemoteSourceIconTooltipControl.TooltipText = songEntry.SongMeta.RemoteSource.NullToEmpty();
        songRatingIconControl.UpdateSongRatingIcons(songEntry.SongMeta, settings.Difficulty);
    }

    private void UpdateLabels()
    {
        if (SongSelectEntry is SongSelectSongEntry songEntry)
        {
            songArtist.text = songEntry.SongMeta.Artist;
            songTitle.text = songEntry.SongMeta.Title;
        }
        else if (SongSelectEntry is SongSelectFolderEntry folderEntry)
        {
            songTitle.text = folderEntry.DirectoryInfo.Name;
            songArtist.text = "";
        }
        else
        {
            songTitle.text = "";
            songArtist.text = "";
        }
    }

    public void Dispose()
    {
        SongSelectEntry = null;
        UnregisterCallbacks();
    }

    public void OpenContextMenu()
    {
        if (!isPopupMenuOpen)
        {
            ContextMenuPopupControl contextMenuPopupControl = contextMenuControl?.OpenContextMenu(new Vector2(
                openSongMenuButton.worldBound.xMin,
                openSongMenuButton.worldBound.yMin));
            contextMenuPopupControl?.VisualElement.Q<Button>().Focus();
        }
    }

    public void Update()
    {
        if (SongSelectEntry is SongSelectSongEntry songEntry
            && (songEntry.SongMeta?.Cover != lastSongMetaCover
                || songEntry.SongMeta?.Background != lastSongMetaBackground))
        {
            Debug.Log($"Updating cover image because cover or background changed in song '{SongMetaUtils.GetArtistDashTitle(songEntry.SongMeta)}'");
            UpdateCover();
        }
    }
}
