using System;
using Unity.Netcode;

namespace CommonOnlineMultiplayer
{
    /**
     * Data structure for the ID that is generated by Unity's Netcode for GameObject,
     * i.e. NetworkManager.Singleton.LocalClientId.
     *
     * NOTE: A Netcode client is named LobbyMember in most of the code.
     */
    [Serializable]
    public struct UnityNetcodeClientId : INetworkSerializable
    {
        private ulong value;
        public ulong Value => value;

        public UnityNetcodeClientId(ulong value)
        {
            this.value = value;
        }

        public static implicit operator UnityNetcodeClientId(ulong value) => new UnityNetcodeClientId(value);

        public static implicit operator ulong(UnityNetcodeClientId value) => value.value;

        public override string ToString() => this.value.ToString();

        public bool IsValid => this.value > 0UL;

        public void NetworkSerialize<T>(BufferSerializer<T> serializer) where T : IReaderWriter
        {
            serializer.SerializeValue(ref value);
        }
    }
}
