namespace CommonOnlineMultiplayer
{
    /**
     * Data structure for the ID that is generated by Unity's Netcode for GameObject,
     * namely NetworkManager.Singleton.LocalClientId.
     */
    public readonly struct UnityNetcodeClientId
    {
        private readonly ulong value;
        public ulong Value => value;

        public UnityNetcodeClientId(ulong value)
        {
            this.value = value;
        }

        public static implicit operator UnityNetcodeClientId(ulong value) => new UnityNetcodeClientId(value);

        public static implicit operator ulong(UnityNetcodeClientId value) => value.value;

        public override string ToString() => this.value.ToString();

        public bool IsValid => this.value > 0UL;
    }
}
