@startuml "assembly-dependencies"

' ---------------------------
' Assets/Plugins
component [Plugins] {
    [CompileTimeTracker]
    [CSharpSynthForUnity]
    [FullSerializer]
    [LeanTween]
    [NLayer]
    [SharpZipLib]
    [Threads]
    [UniInject]
    [UniRx]
    [TextMesh Pro]
}

' ---------------------------
' Assets/Common
[Common]

' ---------------------------
' Assets/Scenes
[Scenes]
[SongEditorScene]
[Demos]

' ---------------------------
' Assets/Editor
[USPlayEditor]
[USPlayEditorTests]

' ---------------------------
' Unity environment
[NUnit]

' ---------------------------
' Dependencies

Common --> Plugins

Scenes --> Common
SongEditorScene --> Common
Demos --> Common

USPlayEditor --> Common

USPlayEditorTests --> Common
USPlayEditorTests --> Scenes
USPlayEditorTests --> NUnit

@enduml