name: Build Companion App

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  PROJECT_PATH: UltraStar Play Companion

jobs:
  build-job:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 6000.1.3f1
        targetPlatform:
          # TODO: Android build has "JDK not found" issue, https://github.com/game-ci/unity-builder/issues/489
          #- Android
          - iOS
    steps:
      # Clone repo and restore cache
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v4
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ env.PROJECT_PATH }}-${{ matrix.targetPlatform }}-${{ hashFiles(env.PROJECT_PATH) }}
          restore-keys: |
            Library-${{ env.PROJECT_PATH }}-${{ matrix.targetPlatform }}-
            Library-${{ env.PROJECT_PATH }}-
            Library-
      
      # Run setup script
      - name: Setup Script
        run: bash build.sh RestoreCompanionAppDependencies

      # Build Executables.
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'
          allowDirtyBuild: true
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targetPlatform }}-build
          path: build/${{ matrix.targetPlatform }}
